# Generated by Django 6.0.5 on 2026-06-06 04:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.kanbanboard')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['board', 'position'], name='columns_kan_board_i_554528_idx')],
                'constraints': [models.UniqueConstraint(fields=('board', 'position'), name='unique_board_column_position'), models.UniqueConstraint(models.F('board'), django.db.models.functions.text.Lower('name'), name='unique_board_column_name_case_insensitive')],
            },
        ),
    ]
