# Generated by Django 6.0.5 on 2026-06-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Por hacer'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Completado')], default='TODO', max_length=15)),
                ('estimated_hours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_stories.userstory')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_story', 'created_at'], name='tasks_techn_user_st_0f3d78_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_story', 'title'), name='unique_story_task_title')],
            },
        ),
    ]
