# Generated by Django 6.0.5 on 2026-06-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CHANGES_REQUESTED', 'Ajustes solicitados')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='userstory',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstory',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
