# Generated by Django 6.0.5 on 2026-06-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('user_stories', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='user_stories.userstory'),
        ),
    ]
