# Generated by Django 6.0.5 on 2026-06-06 20:01

from django.db import migrations, models

def populate_positions(apps, schema_editor):
    KanbanColumn = apps.get_model('columns', 'KanbanColumn')
    for col in KanbanColumn.objects.all():
        cards = col.cards.all().order_by('created_at')
        for idx, card in enumerate(cards):
            card.position = idx
            card.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_kanbancard_user_story'),
        ('columns', '0001_initial'),
        ('user_stories', '0002_userstory_approval_status_userstory_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbancard',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='kanbancard',
            name='cards_kanba_column__66d471_idx',
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_positions),
        migrations.AddIndex(
            model_name='kanbancard',
            index=models.Index(fields=['column', 'position'], name='cards_kanba_column__9291ba_idx'),
        ),
    ]

