# Generated by Django 6.0.5 on 2026-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PO', 'Product Owner'), ('DEV', 'Developer')], default='DEV', max_length=15),
        ),
    ]
