# Generated by Django 6.0.5 on 2026-06-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def populate_default_roles_and_link(apps, schema_editor):
    Role = apps.get_model('authentication', 'Role')
    CustomUser = apps.get_model('authentication', 'CustomUser')
    
    # Create roles
    po_role, _ = Role.objects.get_or_create(
        name='PRODUCT_OWNER',
        description='Dueño del Producto Scrum. Aprueba, rechaza y crea historias de usuario.'
    )
    sm_role, _ = Role.objects.get_or_create(
        name='SCRUM_MASTER',
        description='Facilitador Scrum. Administra columnas y flujos del tablero.'
    )
    dev_role, _ = Role.objects.get_or_create(
        name='DEVELOPER',
        description='Desarrollador. Crea tareas y mueve tarjetas en el tablero.'
    )
    
    # Link existing users
    for user in CustomUser.objects.all():
        if user.role == 'PO':
            user.role_relation = po_role
        elif user.role == 'SM':
            user.role_relation = sm_role
        else:
            user.role_relation = dev_role
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PO', 'Product Owner'), ('DEV', 'Developer'), ('SM', 'Scrum Master')], default='DEV', max_length=15),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.role'),
        ),
        migrations.RunPython(populate_default_roles_and_link),
    ]

